#!/usr/bin/env bash
# Oh! dsh one-command install (Ubuntu 24, single host, all-in-one):
# DSH node container + manager systemd service.
#
# Usage:
#   git clone https://github.com/litestartup-com/dsh-agent-manager.git
#   cd dsh-agent-manager && sudo ./install.sh
#
# Idempotent: existing configs (.env / manager.config.yaml / docker/.env) are
# never overwritten. Non-interactive: every value can be preset via environment
# (GW_KEY / SESSION_SECRET / DEEPSEEK_API_KEY / MANAGER_PASSWORD /
#  WORKSPACE_PATH / MANAGER_PORT); only the missing ones prompt.
# Plan-only pass: DRY_RUN=1 sudo ./install.sh
#
# Note: script output is intentionally English — a minimal server locale
# (LANG=C) would garble non-ASCII text.
set -euo pipefail

APP_ROOT="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_PATH="${WORKSPACE_PATH:-$(dirname "$APP_ROOT")/workspace}"
MANAGER_PORT="${MANAGER_PORT:-8080}"
GW_KEY="${GW_KEY:-}"
SESSION_SECRET="${SESSION_SECRET:-}"
DEEPSEEK_API_KEY="${DEEPSEEK_API_KEY:-}"
MANAGER_USERNAME="${MANAGER_USERNAME:-admin}"
MANAGER_PASSWORD="${MANAGER_PASSWORD:-}"
DRY_RUN="${DRY_RUN:-0}"

RUN_USER="${SUDO_USER:-$(whoami)}"
HOST_UID="$(id -u "$RUN_USER")"
HOST_GID="$(id -g "$RUN_USER")"

log() { echo "[install] $*"; }
run() { if [ "$DRY_RUN" = "1" ]; then log "DRY: $*"; else "$@"; fi }
gen() { openssl rand -hex 32; }

# ---- preflight ----
[ "$(id -u)" = "0" ] || { echo "Run with sudo: sudo ./install.sh"; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "Docker not found. Ubuntu 24: https://docs.docker.com/engine/install/ubuntu/ — install it and re-run."; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "docker compose (v2 plugin) not available."; exit 1; }
command -v node >/dev/null 2>&1 || { echo "Node.js not found (>= 20 required). Install it and re-run."; exit 1; }
MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$MAJOR" -ge 20 ] || { echo "Node.js too old ($MAJOR), >= 20 required."; exit 1; }

log "APP_ROOT=$APP_ROOT"
log "WORKSPACE_PATH=$WORKSPACE_PATH"
log "run as $RUN_USER (uid=$HOST_UID gid=$HOST_GID)"

# ---- secrets ----
[ -n "$GW_KEY" ] || GW_KEY="$(gen)"
[ -n "$SESSION_SECRET" ] || SESSION_SECRET="$(gen)"
if [ "$DRY_RUN" = "1" ]; then
  [ -n "$DEEPSEEK_API_KEY" ] || DEEPSEEK_API_KEY="(not provided in dry run)"
  [ -n "$MANAGER_PASSWORD" ] || MANAGER_PASSWORD="(not provided in dry run)"
else
  if [ -z "$DEEPSEEK_API_KEY" ]; then read -rp "DeepSeek API key (empty = configure it later in the DSH GUI): " DEEPSEEK_API_KEY || true; fi
  if [ -z "$MANAGER_PASSWORD" ]; then
    read -rsp "Manager initial password (empty = generate one): " MANAGER_PASSWORD; echo
    [ -n "$MANAGER_PASSWORD" ] || MANAGER_PASSWORD="$(gen | cut -c1-16)"
  fi
fi

# ---- configs (never overwrite) ----
if [ -f .env ]; then
  log "skip (exists): .env"
else
  sed -e "s|^SESSION_SECRET=.*|SESSION_SECRET=$SESSION_SECRET|" \
      -e "s|^MANAGER_USERNAME=.*|MANAGER_USERNAME=$MANAGER_USERNAME|" \
      -e "s|^MANAGER_INITIAL_PASSWORD=.*|MANAGER_INITIAL_PASSWORD=$MANAGER_PASSWORD|" \
      -e "s|^GW_KEY_A=.*|GW_KEY_A=$GW_KEY|" \
      .env.example > .env
  log "created: .env"
fi

if [ -f manager.config.yaml ]; then
  log "skip (exists): manager.config.yaml"
else
  cat > manager.config.yaml <<EOF
# Generated by install.sh — same-host scheme B (via the node container's
# dsh-api-gateway, key auth).
listen:
  host: 127.0.0.1
  port: $MANAGER_PORT

endpoints:
  A:
    url: http://127.0.0.1:3080
    driver: apiproxy
    prefix: /api-gw/v1/proxy
    key_ref: GW_KEY_A

agents:
  personal:
    name: 个人
    endpoint: A
    workspace: $WORKSPACE_PATH
    public: false

runner:
  timeout_minutes: 15
  silence_timeout_minutes: 5
  max_consecutive_failures: 3
  daily_budget_usd: 2.0

database:
  path: ./data/manager.db

pricing:
  peak_windows_utc:
    - { start: '01:00', end: '04:00' }
    - { start: '06:00', end: '10:00' }
  models:
    deepseek-v4-pro:
      off_peak: { input: 0.66, output: 1.98, cache_read: 0.022 }
      peak: { input: 1.32, output: 3.96, cache_read: 0.044 }
    deepseek-v4-flash:
      off_peak: { input: 0.22, output: 0.66, cache_read: 0.007 }
      peak: { input: 0.44, output: 1.32, cache_read: 0.014 }
EOF
  log "created: manager.config.yaml (endpoint A over the gateway, scheme B)"
fi

if [ -f docker/.env ]; then
  log "skip (exists): docker/.env"
else
  cat > docker/.env <<EOF
# Generated by install.sh
GW_KEY=$GW_KEY
DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
WORKSPACE_PATH=$WORKSPACE_PATH
HOST_UID=$HOST_UID
HOST_GID=$HOST_GID
EOF
  log "created: docker/.env"
fi

# ---- directories (host and container share the uid) ----
run mkdir -p "$WORKSPACE_PATH"
run chown -R "$HOST_UID:$HOST_GID" "$WORKSPACE_PATH"
# The manager's SQLite dir must belong to the service user (npm ran as root).
run mkdir -p "$APP_ROOT/data"
run chown -R "$HOST_UID:$HOST_GID" "$APP_ROOT/data"
if [ "$HOST_UID" != "1000" ]; then
  log "NOTE: HOST_UID=$HOST_UID (not 1000). The container volume is initialised for uid 1000;"
  log "      see docker/README.md if the container reports write-permission errors."
fi

# ---- node container ----
if [ "$DRY_RUN" = "1" ]; then
  log "DRY: docker compose up -d --build (docker/)"
else
  log "Building the node container (first build takes 2-5 min)..."
  (cd docker && docker compose up -d --build)
fi

# ---- manager ----
run npm install
run npm run build

# ---- systemd ----
if command -v systemctl >/dev/null 2>&1; then
  NODE_BIN="$(command -v node)"
  if [ "$DRY_RUN" = "1" ]; then
    log "DRY: write /etc/systemd/system/ohdsh-manager.service + enable --now"
  else
    sed -e "s|__APP_ROOT__|$APP_ROOT|g" \
        -e "s|__RUN_USER__|$RUN_USER|g" \
        -e "s|__NODE_BIN__|$NODE_BIN|g" \
        deploy/ohdsh-manager.service > /etc/systemd/system/ohdsh-manager.service
    systemctl daemon-reload
    systemctl enable --now ohdsh-manager
    log "systemd service started: journalctl -u ohdsh-manager -f"
  fi
else
  log "no systemd: run the manager yourself, e.g. nohup node dist/index.js &"
fi

# ---- summary ----
cat <<EOF

============================================================
Installed.
  manager:    http://127.0.0.1:$MANAGER_PORT  (user: $MANAGER_USERNAME)
  node:       docker compose -f $APP_ROOT/docker/docker-compose.yml ps
  workspace:  $WORKSPACE_PATH

Acceptance (from $APP_ROOT):
  export SMOKE_KEY="$(grep '^GW_KEY=' docker/.env | cut -d= -f2)"
  npx tsx scripts/smoke-proxy-b.ts http://127.0.0.1:3080/api-gw/v1/proxy
  ./docker/smoke.sh
============================================================
EOF
